<?php
/**
 * Rock Paper Scissors - Configuration File
 * This file is generated by install.php
 */

// Prevent direct access
if (!defined('RPS_GAME')) {
    die('Direct access not permitted');
}

// Database Configuration
define('DB_HOST', '{{DB_HOST}}');
define('DB_NAME', '{{DB_NAME}}');
define('DB_USER', '{{DB_USER}}');
define('DB_PASS', '{{DB_PASS}}');

// Application Settings
define('SITE_NAME', 'RPS Arena');
define('SITE_URL', '{{SITE_URL}}');

// Game Settings
define('DEFAULT_MAX_ROUNDS', 3);        // Best of 3
define('MOVE_TIMEOUT_SECONDS', 30);     // Seconds to make a move
define('QUEUE_TIMEOUT_SECONDS', 300);   // 5 minutes max in queue
define('ONLINE_THRESHOLD_SECONDS', 300); // Consider online if active within 5 min

// Private Games
define('PRIVATE_ROOM_TIMEOUT_SECONDS', 600); // 10 minutes to join
define('PRIVATE_ROOM_CODE_LENGTH', 6);       // Length of generated codes
define('PRIVATE_ROOM_MAX_ACTIVE', 1);        // Max active rooms per user

// Rating System (Simple ELO)
define('RATING_K_FACTOR', 32);          // How much ratings change per game
define('RATING_START', 1000);           // Starting rating for new players

// Security
define('CSRF_TOKEN_NAME', 'rps_csrf_token');
define('SESSION_LIFETIME', 86400);      // 24 hours
define('REMEMBER_ME_DAYS', 30);

// Polling Intervals (milliseconds) - for JavaScript
define('POLL_LOBBY', 5000);             // Lobby updates
define('POLL_QUEUE', 2000);             // Matchmaking queue
define('POLL_GAME', 1500);              // In-game updates

// Debug Mode (set to false in production)
define('DEBUG_MODE', false);
